stages:
  - build

build:
  stage: build
  image: docker:latest
  variables:
    CI_DEBUG_TRACE: "true"
    DOCKER_HOST: tcp://localhost:2375

  services:
    - docker:dind

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
